server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  # Redirect root to /docs/
  location = / {
    return 302 /docs/;
  }

  # Serve static
  location / {
    try_files $uri $uri/ =404;
  }
}

